setw -g default-terminal "screen-256color"
setw -g mode-keys vi

#setw -g status-bg black
setw -g status-bg '#1a1a1a'
setw -g status-fg white

bind -n S-Enter send-keys "[13;2u"

set-option -g default-shell /usr/bin/zsh

set-option -g history-limit 3000

set -g focus-events on

setw -g mouse on

set -sg escape-time 10

set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind h split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

